{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "dokuwiki.fullname" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
  {{- end }}
  {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
  {{- if .Values.ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- $tls := false }}
  {{- range .Values.ingress.hosts  }}
  {{- if .tls }}
    {{- $tls = true }}
  {{- end }}
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "dokuwiki.fullname" $ }}
            servicePort: 80
  {{- end }}
  {{- if $tls }}
  tls:
  {{- range .Values.ingress.hosts  }}
  {{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
